import type { Grade, Incumbent, Offer, OfferScenario, OfferSettings } from '../types/domain'

/**
 * A synthetic team, generated by code. No real pay data ever enters this
 * repository — see CLAUDE.md constraint 4.
 *
 * It exists so the tool demonstrates itself before anyone types anything, and
 * it is built to contain a real compression trap rather than a tidy population:
 * a tidy sample would show a practitioner nothing they could not already guess.
 *
 * The trap. Grade 4 has been hiring through a market that moved faster than the
 * merit budget, so the newest arrivals sit near the top of the grade and the
 * people who have been there five years sit near the bottom. The offer that
 * loads with it lands at the market rate for the role — and lands above four
 * long-tenured incumbents, one of whom is a strong performer, while one person
 * a whole grade up is already paid less than the offer.
 *
 * Everything below is deterministic. There is no randomness, so the numbers on
 * screen are the same for every user and can be checked against the tests.
 */

export const SAMPLE_GRADES: Grade[] = [
  { id: 'G1', name: 'Grade 1 — Associate', order: 1, min: 52_000, mid: 63_000, max: 74_000 },
  { id: 'G2', name: 'Grade 2 — Analyst', order: 2, min: 62_000, mid: 76_000, max: 90_000 },
  { id: 'G3', name: 'Grade 3 — Senior Analyst', order: 3, min: 74_000, mid: 92_000, max: 110_000 },
  { id: 'G4', name: 'Grade 4 — Lead', order: 4, min: 88_000, mid: 111_000, max: 134_000 },
  { id: 'G5', name: 'Grade 5 — Manager', order: 5, min: 106_000, mid: 134_000, max: 162_000 },
]

/**
 * Forty-one people. Salaries are written out rather than generated from a
 * distribution, because a reader checking whether the tool is right needs to be
 * able to check the input by eye.
 */
export const SAMPLE_TEAM: Incumbent[] = [
  // Grade 1 — junior, unremarkable, no findings expected.
  { id: 'A-104', gradeId: 'G1', baseSalary: 54_200, fte: 1, hireDate: '2023-09-05', performanceRating: 'Meets', managerId: 'A-411' },
  { id: 'A-118', gradeId: 'G1', baseSalary: 57_800, fte: 1, hireDate: '2022-04-11', performanceRating: 'Meets', managerId: 'A-411' },
  { id: 'A-126', gradeId: 'G1', baseSalary: 61_500, fte: 1, hireDate: '2021-02-01', performanceRating: 'Exceeds', managerId: 'A-411' },
  { id: 'A-133', gradeId: 'G1', baseSalary: 53_000, fte: 0.6, hireDate: '2024-01-15', performanceRating: 'Meets', managerId: 'A-411' },
  { id: 'A-141', gradeId: 'G1', baseSalary: 65_900, fte: 1, hireDate: '2019-06-03', performanceRating: 'Meets', managerId: 'A-411' },

  // Grade 2.
  { id: 'A-205', gradeId: 'G2', baseSalary: 64_300, fte: 1, hireDate: '2023-11-20', performanceRating: 'Meets', managerId: 'A-411' },
  { id: 'A-212', gradeId: 'G2', baseSalary: 71_000, fte: 1, hireDate: '2022-01-10', performanceRating: 'Meets', managerId: 'A-411' },
  { id: 'A-219', gradeId: 'G2', baseSalary: 78_400, fte: 1, hireDate: '2020-08-17', performanceRating: 'Exceeds', managerId: 'A-411' },
  { id: 'A-227', gradeId: 'G2', baseSalary: 69_800, fte: 1, hireDate: '2023-03-06', performanceRating: 'Meets', managerId: 'A-418' },
  { id: 'A-234', gradeId: 'G2', baseSalary: 84_100, fte: 1, hireDate: '2018-05-14', performanceRating: 'Meets', managerId: 'A-418' },
  { id: 'A-240', gradeId: 'G2', baseSalary: 40_500, fte: 0.5, hireDate: '2021-09-27', performanceRating: 'Meets', managerId: 'A-418' },
  { id: 'A-248', gradeId: 'G2', baseSalary: 75_600, fte: 1, hireDate: '2021-11-08', performanceRating: 'Outstanding', managerId: 'A-418' },

  // Grade 3.
  { id: 'A-302', gradeId: 'G3', baseSalary: 79_500, fte: 1, hireDate: '2022-10-03', performanceRating: 'Meets', managerId: 'A-418' },
  { id: 'A-309', gradeId: 'G3', baseSalary: 88_200, fte: 1, hireDate: '2020-01-13', performanceRating: 'Exceeds', managerId: 'A-418' },
  { id: 'A-315', gradeId: 'G3', baseSalary: 94_700, fte: 1, hireDate: '2017-07-24', performanceRating: 'Meets', managerId: 'A-425' },
  { id: 'A-322', gradeId: 'G3', baseSalary: 82_900, fte: 1, hireDate: '2023-06-19', performanceRating: 'Meets', managerId: 'A-425' },
  { id: 'A-330', gradeId: 'G3', baseSalary: 101_300, fte: 1, hireDate: '2015-03-02', performanceRating: 'Outstanding', managerId: 'A-425' },
  { id: 'A-337', gradeId: 'G3', baseSalary: 86_400, fte: 1, hireDate: '2021-05-11', performanceRating: 'Meets', managerId: 'A-425' },
  { id: 'A-344', gradeId: 'G3', baseSalary: 91_000, fte: 1, hireDate: '2019-09-30', performanceRating: 'Exceeds', managerId: 'A-425' },
  { id: 'A-351', gradeId: 'G3', baseSalary: 77_800, fte: 1, hireDate: '2024-02-05', performanceRating: 'Meets', managerId: 'A-425' },

  // Grade 4 — the offer's grade, and where the trap lives.
  // Long tenure sits below the two most recent arrivals: five years of merit at
  // 3% against a market that moved 5%. The grade is uncomfortable rather than
  // broken, which is the state a practitioner actually walks into.
  { id: 'A-402', gradeId: 'G4', baseSalary: 108_500, fte: 1, hireDate: '2016-04-18', performanceRating: 'Exceeds', managerId: 'A-511' },
  { id: 'A-408', gradeId: 'G4', baseSalary: 110_200, fte: 1, hireDate: '2018-02-26', performanceRating: 'Meets', managerId: 'A-511' },
  { id: 'A-411', gradeId: 'G4', baseSalary: 112_900, fte: 1, hireDate: '2017-11-06', performanceRating: 'Meets', managerId: 'A-511' },
  // Six years in, rated Outstanding, and about to be leapfrogged. The finding
  // the whole tool exists to put in front of somebody.
  { id: 'A-418', gradeId: 'G4', baseSalary: 109_700, fte: 1, hireDate: '2019-08-12', performanceRating: 'Outstanding', managerId: 'A-511' },
  { id: 'A-425', gradeId: 'G4', baseSalary: 116_400, fte: 1, hireDate: '2020-06-01', performanceRating: 'Meets', managerId: 'A-511' },
  { id: 'A-431', gradeId: 'G4', baseSalary: 55_600, fte: 0.5, hireDate: '2018-10-22', performanceRating: 'Meets', managerId: 'A-511' },
  { id: 'A-437', gradeId: 'G4', baseSalary: 118_300, fte: 1, hireDate: '2023-01-09', performanceRating: 'Meets', managerId: 'A-511' },
  // Hired seven months ago at the top of the grade: market-set, so reported
  // and never flagged.
  { id: 'A-443', gradeId: 'G4', baseSalary: 121_000, fte: 1, hireDate: '2024-04-15', performanceRating: 'Meets', managerId: 'A-511' },
  { id: 'A-449', gradeId: 'G4', baseSalary: 119_700, fte: 1, hireDate: '2022-07-25', performanceRating: 'Exceeds', managerId: 'A-518' },
  { id: 'A-455', gradeId: 'G4', baseSalary: 114_300, fte: 1, hireDate: '2021-03-08', performanceRating: 'Meets', managerId: 'A-518' },
  // Hired three months ago and below everyone: the case the tenure gate is
  // weakest against, and the reason the two ceilings differ on screen.
  { id: 'A-468', gradeId: 'G4', baseSalary: 104_000, fte: 1, hireDate: '2024-08-05', performanceRating: 'Meets', managerId: 'A-518' },
  // No hire date: the tenure-unknown case, which a real export produces often.
  { id: 'A-462', gradeId: 'G4', baseSalary: 115_100, fte: 1, performanceRating: 'Meets', managerId: 'A-518' },

  // Grade 5 — including one person a whole grade up who is already paid less
  // than the offer. The offer did not cause that; it exposes it.
  { id: 'A-504', gradeId: 'G5', baseSalary: 109_800, fte: 1, hireDate: '2016-09-19', performanceRating: 'Meets', managerId: 'A-601' },
  { id: 'A-511', gradeId: 'G5', baseSalary: 138_500, fte: 1, hireDate: '2018-01-22', performanceRating: 'Exceeds', managerId: 'A-601' },
  { id: 'A-518', gradeId: 'G5', baseSalary: 131_200, fte: 1, hireDate: '2019-05-07', performanceRating: 'Meets', managerId: 'A-601' },
  { id: 'A-524', gradeId: 'G5', baseSalary: 145_900, fte: 1, hireDate: '2014-11-03', performanceRating: 'Outstanding', managerId: 'A-601' },
  { id: 'A-531', gradeId: 'G5', baseSalary: 126_700, fte: 1, hireDate: '2022-02-14', performanceRating: 'Meets', managerId: 'A-601' },
  { id: 'A-537', gradeId: 'G5', baseSalary: 133_800, fte: 1, hireDate: '2020-10-26', performanceRating: 'Meets', managerId: 'A-601' },
  { id: 'A-601', gradeId: 'G5', baseSalary: 158_200, fte: 1, hireDate: '2013-06-10', performanceRating: 'Exceeds' },

  // A few more in the lower grades, so the team reads as an org rather than a
  // demonstration of exactly the cases the tool handles.
  { id: 'A-152', gradeId: 'G1', baseSalary: 59_400, fte: 1, hireDate: '2022-11-28', performanceRating: 'Meets', managerId: 'A-411' },
  { id: 'A-256', gradeId: 'G2', baseSalary: 81_700, fte: 1, hireDate: '2019-01-07', performanceRating: 'Exceeds', managerId: 'A-418' },
  { id: 'A-358', gradeId: 'G3', baseSalary: 96_100, fte: 1, hireDate: '2018-08-20', performanceRating: 'Meets', managerId: 'A-425' },
]

/**
 * The offer that loads with the sample: a Grade 4 lead, priced a little under
 * market because the recruiter already tried market and finance said no.
 *
 * $112,000 is above four tenured incumbents including the Outstanding performer,
 * inside the compression threshold of three more, and above A-504, who sits a
 * whole grade higher. It is also well above the clean ceiling, which is the
 * point: the first screen a practitioner sees should show them a decision with
 * a price on it, not a clean bill of health.
 */
export const SAMPLE_OFFER: Offer = {
  label: 'Req 4412',
  gradeId: 'G4',
  baseSalary: 112_000,
  fte: 1,
  startDate: '2024-11-01',
  managerId: 'A-511',
  marketReference: 118_000,
  marketReferenceLabel: '50th percentile, national',
}

export const DEFAULT_SETTINGS: OfferSettings = {
  peerCompressionThreshold: 0.05,
  verticalDifferentialThreshold: 0.15,
  tenureQualifyingMonths: 12,
  remediationTarget: 'auto',
  strongRatings: ['Exceeds', 'Outstanding'],
  currency: 'USD',
  locale: 'en-US',
}

export function sampleScenario(): OfferScenario {
  return {
    name: 'Sample team — Req 4412',
    incumbents: SAMPLE_TEAM,
    grades: SAMPLE_GRADES,
    offer: SAMPLE_OFFER,
    settings: DEFAULT_SETTINGS,
  }
}
